# src/kr20_kr120_description/config/controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    kr20_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    kr120_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    kr120_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# ---- Per-controller parameters (must be separate node sections) ----
kr20_arm_controller:
  ros__parameters:
    joints:
      - kr20_base_link__link1
      - kr20_link1__link2
      - kr20_link2__link3
      - kr20_link3__link4
      - kr20_link4__link5
      - kr20_link5__flange
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false

kr120_arm_controller:
  ros__parameters:
    joints:
      - kr120_base_link__link1
      - kr120_link1__link2
      - kr120_link2__link3
      - kr120_link3__link4
      - kr120_link4__link5
      - kr120_link5__flange
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false

kr120_gripper_controller:
  ros__parameters:
    joints:
      - kr120_pinza_left_joint
      - kr120_pinza_right_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.1


# controller_manager:
#   ros__parameters:
#     update_rate: 500

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     kr20_arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController

#     kr120_arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController

# kr20_arm_controller:
#   ros__parameters:
#     joints:
#       - kr20_base_link__link1
#       - kr20_link1__link2
#       - kr20_link2__link3
#       - kr20_link3__link4
#       - kr20_link4__link5
#       - kr20_link5__flange
#     command_interfaces: [position]
#     state_interfaces: [position, velocity]

# kr120_arm_controller:
#   ros__parameters:
#     joints:
#       - kr120_base_link__link1
#       - kr120_link1__link2
#       - kr120_link2__link3
#       - kr120_link3__link4
#       - kr120_link4__link5
#       - kr120_link5__flange
#     command_interfaces: [position]
#     state_interfaces: [position, velocity]

# kr120_gripper_controller:
#   type: joint_trajectory_controller/JointTrajectoryController
#   joints:
#     - kr120_pinza_left_joint
#     - kr120_pinza_right_joint
#   command_interfaces: [position]
#   state_interfaces: [position, velocity]
#   allow_partial_joints_goal: false

