# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  kr120_base_link__link1:
    has_velocity_limits: true
    max_velocity: 2.0943999999999998
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr120_link1__link2:
    has_velocity_limits: true
    max_velocity: 2.0071300000000001
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr120_link2__link3:
    has_velocity_limits: true
    max_velocity: 2.0943999999999998
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr120_link3__link4:
    has_velocity_limits: true
    max_velocity: 3.3161299999999998
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr120_link4__link5:
    has_velocity_limits: true
    max_velocity: 3.1415899999999999
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr120_link5__flange:
    has_velocity_limits: true
    max_velocity: 4.5378600000000002
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_base_link__link1:
    has_velocity_limits: true
    max_velocity: 3.4906600000000001
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link1__link2:
    has_velocity_limits: true
    max_velocity: 3.0543300000000002
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link2__link3:
    has_velocity_limits: true
    max_velocity: 3.3161299999999998
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link3__link4:
    has_velocity_limits: true
    max_velocity: 7.5049200000000003
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link4__link5:
    has_velocity_limits: true
    max_velocity: 7.5049200000000003
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link5__flange:
    has_velocity_limits: true
    max_velocity: 10.9956
    has_acceleration_limits: false
    max_acceleration: 0.0
    kr20_link1__link2:
    has_velocity_limits: true
    max_velocity: 3.05433
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link2__link3:
    has_velocity_limits: true
    max_velocity: 3.31613
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link3__link4:
    has_velocity_limits: true
    max_velocity: 7.50492
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link4__link5:
    has_velocity_limits: true
    max_velocity: 7.50492
    has_acceleration_limits: false
    max_acceleration: 0.0
  kr20_link5__flange:
    has_velocity_limits: true
    max_velocity: 10.9956
    has_acceleration_limits: false
    max_acceleration: 0.0
  rl_base__lifter:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  rl_base__slider:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  rl_slider__plate:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0