robot_description_kinematics:
  kr20_arm:
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_timeout: 0.05
    solve_type: Speed
  kr120_arm:
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_timeout: 0.05
    solve_type: Speed
